version: '3.3'
services:
  bot:
    build: .
    environment:
      BOT_TOKEN: "BOT_TOKEN"
  db:
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
